"""Canonical Nuitka build flag definitions.

This module is the single source of truth for the arguments passed to
``python -m nuitka`` when packaging Impulcifer. Both
:mod:`build_scripts.build_nuitka` (used by the Windows release workflow) and
the GitHub Actions ``build-linux.yml`` / ``build-macos.yml`` workflows should
ultimately consume the values defined here.

The flag list is split into named groups so callers can compose them:

* :data:`COMMON_FLAGS` — platform-independent Nuitka switches
* :data:`INCLUDED_PACKAGES` / :data:`INCLUDED_MODULES` — `--include-package` /
  `--include-module` lists
* :data:`INCLUDED_DATA_DIRS` / :data:`INCLUDED_DATA_FILES` — data assets
* :data:`METADATA_FLAGS` — name/version metadata template (callers must
  substitute version)

Use :func:`build_nuitka_args` to assemble the full argument list for a given
platform and version.
"""

from __future__ import annotations

import os
from typing import List, Optional, Sequence


# ---------------------------------------------------------------------------
# Common (platform-independent) flags
# ---------------------------------------------------------------------------
COMMON_FLAGS: tuple[str, ...] = (
    "--standalone",
    "--remove-output",
    "--jobs=4",
    "--lto=no",
    # Plugins. tk-inter and matplotlib bundle non-Python data files Nuitka
    # would otherwise miss; multiprocessing / pkg-resources / anti-bloat are
    # auto-enabled by Nuitka itself and are NOT listed here intentionally.
    "--enable-plugin=tk-inter",
    "--enable-plugin=matplotlib",
    "--prefer-source-code",
    "--assume-yes-for-downloads",
    "--show-progress",
    "--show-memory",
)


# Output directory mapping per target platform
PLATFORM_OUTPUT_DIRS: dict[str, str] = {
    "windows": "dist/Impulcifer_Distribution/ImpulciferGUI",
    "macos": "dist/macos",
    "linux": "dist/linux",
}

PLATFORM_OUTPUT_FILENAMES: dict[str, str] = {
    "windows": "ImpulciferGUI",
    "macos": "Impulcifer",
    "linux": "Impulcifer",
}


# ---------------------------------------------------------------------------
# Module / package inclusion lists
# ---------------------------------------------------------------------------
INCLUDED_PACKAGES: tuple[str, ...] = (
    # CustomTkinter ships JSON theme files and PNG assets that Nuitka's
    # static analysis won't pull in by import — keep as a package include.
    "customtkinter",
    # NOTE: pywebview (the WebView frontend, launcher default since 2.10) is
    # deliberately NOT listed here — and must not be added to
    # INCLUDED_MODULES either. Any --include-module/--include-package entry
    # feeds Nuitka's follow patterns for the whole subtree, which conflicts
    # with the auto-enabled 'pywebview' plugin excluding other platforms'
    # backend modules (observed FATAL: "Conflict between user and plugin
    # decision for module 'webview.platforms.android'"). The static
    # ``import webview`` chain (gui_main → impulcifer_webview) is traced
    # automatically; the plugin selects the platform backend and Nuitka's
    # package config bundles webview/js, webview/lib DLLs and the pythonnet /
    # clr_loader runtime pieces on Windows.
)

# ``--include-package-data`` targets: packages that load non-Python files at
# runtime. (Data-file flags do not feed follow patterns, so unlike module
# includes this cannot conflict with the pywebview plugin.)
INCLUDED_PACKAGE_DATA: tuple[str, ...] = (
    # webview/js/*.js bootstrap + webview/lib DLLs — Nuitka's package config
    # already covers these; kept as belt-and-suspenders against upstream
    # config changes.
    "webview",
)

# Nuitka in --standalone mode follows static (and lazy) imports automatically,
# so the project tree (`core.*`, `gui.*`, `i18n.*`, `infra.*`, `updater.*`,
# `impulcifer`) does NOT need to be enumerated here — those entries were
# verified redundant against Nuitka 4.x's import tracer and removed.
#
# We keep explicit entries only for:
#   1. Heavyweight third-party packages that historically tripped Nuitka's
#      submodule detection (scipy / bokeh).
#   2. Modules that are entered through subprocess / multiprocessing rather
#      than the main thread's import graph (`core.parallel_workers`).
#   3. ``infra._build_info`` which is generated by ``build_nuitka.py`` just
#      before invocation — listed defensively in case the writeback is racy.
INCLUDED_MODULES: tuple[str, ...] = (
    # Heavy third-party — keep belt-and-suspenders for scipy/bokeh
    "scipy.signal",
    "scipy.optimize",
    "scipy.interpolate",
    "scipy.io",
    "scipy.fft",
    "bokeh",
    # Worker module loaded by ProcessPoolExecutor children
    "core.parallel_workers",
    # Build-time generated marker file
    "infra._build_info",
)


# ---------------------------------------------------------------------------
# Data assets — paths relative to project root
# ---------------------------------------------------------------------------
# Each entry is (source, destination_inside_bundle)
INCLUDED_DATA_DIRS: tuple[tuple[str, str], ...] = (
    ("data", "data"),
    ("font", "font"),
    ("img", "img"),
    ("logo", "logo"),
    ("i18n/locales", "i18n/locales"),
    ("gui/theme", "gui/theme"),
    # WebView frontend HTML/CSS/JS — resolved via get_resource_path at the
    # same relative path as in the source tree.
    ("webview_ui", "webview_ui"),
)

INCLUDED_DATA_FILES: tuple[tuple[str, str], ...] = (
    ("LICENSE", "License.txt"),
    ("README.txt", "README.txt"),
    # 서드파티 재배포 고지 — pywebview(BSD-3)·CustomTkinter(MIT) 코드와
    # AutoEQ(MIT) 벤더링, OFL 폰트가 standalone에 번들되므로 고지 파일도
    # 함께 실린다. (font/OFL-*.txt는 font 데이터 디렉토리에 이미 포함됨.)
    ("THIRD_PARTY_LICENSES.md", "THIRD_PARTY_LICENSES.md"),
    ("autoeq/LICENSE", "autoeq/LICENSE"),
)


# ---------------------------------------------------------------------------
# Metadata flags (callers substitute version & description)
# ---------------------------------------------------------------------------
METADATA_TEMPLATE: tuple[str, ...] = (
    "--company-name=115dkk",
    "--product-name=Impulcifer",
    "--file-description=HRIR 측정 및 헤드폰 바이노럴 헤드트래킹 HRTF 시스템",
)


def _package_exists(name: str) -> bool:
    """Build-time probe: is ``name`` importable in the build environment?"""
    try:
        import importlib.util

        return importlib.util.find_spec(name) is not None
    except (ImportError, ValueError):
        return False


# scipy가 벤더링한 array-api-compat은 백엔드 서브모듈(numpy.fft 등)을 lazy
# import해 Nuitka의 정적 추적에서 누락된다. 2.10.0 릴리스의 standalone이
# 모든 scipy import에서 "No module named 'scipy._external.array_api_compat.
# numpy.fft'"로 즉사한 원인(설치본 실검증으로 발견) — CTk 기동과 WebView
# bootstrap이 함께 죽어 UI 문자열/언어 목록까지 사라졌다. scipy 1.18+는
# scipy._external 아래, 그 이전(1.12~1.17)은 scipy._lib 아래에 있으므로
# 존재하는 쪽을 통째로 포함한다(없는 패키지를 include하면 Nuitka가 에러
# 내므로 빌드 환경 기준으로 조건부).
SCIPY_VENDORED_COMPAT_CANDIDATES: tuple[str, ...] = (
    "scipy._external",
    "scipy._lib.array_api_compat",
)


def scipy_vendored_compat_flags(package_exists=_package_exists) -> List[str]:
    return [
        f"--include-package={name}"
        for name in SCIPY_VENDORED_COMPAT_CANDIDATES
        if package_exists(name)
    ]


def platform_specific_flags(target_platform: str, project_root: str = ".") -> List[str]:
    """Return platform-conditional Nuitka flags.

    Includes window subsystem (Windows), app bundle (macOS), and icon
    inclusion when an icon file exists under ``project_root/img/``.
    """
    flags: List[str] = []
    if target_platform == "windows":
        flags.append("--windows-console-mode=disable")
        # Bundle the multi-resolution Pulse icon so the .exe + taskbar
        # tile + pinned shortcut all show the brand mark instead of the
        # default Windows generic-app icon.
        ico = os.path.join(project_root, "logo", "pulse.ico")
        if os.path.exists(ico):
            flags.append(f"--windows-icon-from-ico={ico}")
    elif target_platform == "macos":
        flags.extend(("--macos-create-app-bundle", "--macos-app-name=Impulcifer"))
        # Prefer the Pulse logo's icns when present; fall back to the
        # legacy img/icon.icns.
        for icns in (
            os.path.join(project_root, "logo", "pulse.icns"),
            os.path.join(project_root, "img", "icon.icns"),
        ):
            if os.path.exists(icns):
                flags.append(f"--macos-app-icon={icns}")
                break
    elif target_platform == "linux":
        for png in (
            os.path.join(project_root, "logo", "pulse-256.png"),
            os.path.join(project_root, "img", "icon.png"),
        ):
            if os.path.exists(png):
                flags.append(f"--linux-icon={png}")
                break
    return flags


def build_nuitka_args(
    target_platform: str,
    version: str,
    project_root: str = ".",
    output_dir: Optional[str] = None,
    output_filename: Optional[str] = None,
    entry_point: str = "gui_main.py",
    jobs: Optional[int] = None,
) -> List[str]:
    """Assemble the complete argument list for ``python -m nuitka``.

    Returns the args without the leading ``["python", "-m", "nuitka"]``.
    The caller can prepend that or pass them to :func:`subprocess.run`.

    ``project_root`` is used to test for optional assets (icons, README.txt,
    LICENSE) so they are only included when they exist.

    ``jobs`` overrides the canonical ``--jobs=4`` from ``COMMON_FLAGS`` for
    callers that need a higher core count (e.g. local fast-iteration builds
    via ``build_scripts/build_local.py``). CI keeps the default of 4 since
    GitHub runners are not always 16-core.
    """
    if output_dir is None:
        output_dir = PLATFORM_OUTPUT_DIRS.get(target_platform, "dist")
    if output_filename is None:
        output_filename = PLATFORM_OUTPUT_FILENAMES.get(target_platform, "Impulcifer")

    if jobs is None:
        common_args = list(COMMON_FLAGS)
    else:
        # Replace the ``--jobs=N`` flag in COMMON_FLAGS so we don't end up
        # with a duplicated flag on the command line (Nuitka would error).
        common_args = [
            f"--jobs={jobs}" if a.startswith("--jobs=") else a
            for a in COMMON_FLAGS
        ]
    args: List[str] = common_args
    args.append(f"--output-dir={output_dir}")
    args.extend(platform_specific_flags(target_platform, project_root))

    for pkg in INCLUDED_PACKAGES:
        args.append(f"--include-package={pkg}")
    for pkg in INCLUDED_PACKAGE_DATA:
        args.append(f"--include-package-data={pkg}")
    for mod in INCLUDED_MODULES:
        args.append(f"--include-module={mod}")
    args.extend(scipy_vendored_compat_flags())

    for src, dst in INCLUDED_DATA_DIRS:
        full_src = os.path.join(project_root, src)
        if os.path.exists(full_src):
            args.append(f"--include-data-dir={src}={dst}")

    for src, dst in INCLUDED_DATA_FILES:
        full_src = os.path.join(project_root, src)
        if os.path.exists(full_src):
            args.append(f"--include-data-file={src}={dst}")

    args.extend(METADATA_TEMPLATE)
    args.append(f"--output-filename={output_filename}")
    args.append(f"--file-version={version}")
    args.append(f"--product-version={version}")
    args.append(entry_point)
    return args


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Tiny CLI: ``python -m build_scripts.nuitka_flags --platform linux --version X``.

    Prints one Nuitka flag per line so a workflow can ``mapfile`` the output
    or feed it into a Nuitka invocation. Exists primarily to keep workflows
    in sync with this Python module without parsing it.
    """
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--platform",
        choices=("windows", "macos", "linux"),
        required=True,
        help="Target build platform.",
    )
    parser.add_argument(
        "--version",
        required=True,
        help="Project version string substituted into --file-version / --product-version.",
    )
    parser.add_argument(
        "--project-root",
        default=".",
        help="Path to the project root (defaults to CWD).",
    )
    args = parser.parse_args(argv)

    flag_list = build_nuitka_args(
        target_platform=args.platform,
        version=args.version,
        project_root=args.project_root,
    )
    for flag in flag_list:
        print(flag)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
