"""Canonical Nuitka build flag definitions (issue #87 Phase 4).

This module is the single source of truth for the arguments passed to
``python -m nuitka`` when packaging Impulcifer. Both
:mod:`build_scripts.build_nuitka` (used by the Windows release workflow) and
the GitHub Actions ``build-linux.yml`` / ``build-macos.yml`` workflows should
ultimately consume the values defined here.

The flag list is split into named groups so callers can compose them:

* :data:`COMMON_FLAGS` — platform-independent Nuitka switches
* :data:`INCLUDED_PACKAGES` / :data:`INCLUDED_MODULES` — `--include-package` /
  `--include-module` lists
* :data:`INCLUDED_DATA_DIRS` / :data:`INCLUDED_DATA_FILES` — data assets
* :data:`METADATA_FLAGS` — name/version metadata template (callers must
  substitute version)

Use :func:`build_nuitka_args` to assemble the full argument list for a given
platform and version.
"""

from __future__ import annotations

import os
from typing import Iterable, List, Optional, Sequence


# ---------------------------------------------------------------------------
# Common (platform-independent) flags
# ---------------------------------------------------------------------------
COMMON_FLAGS: tuple[str, ...] = (
    "--standalone",
    "--remove-output",
    "--jobs=4",
    "--lto=no",
    # Plugins. tk-inter and matplotlib bundle non-Python data files Nuitka
    # would otherwise miss; multiprocessing / pkg-resources / anti-bloat are
    # auto-enabled by Nuitka itself and are NOT listed here intentionally.
    "--enable-plugin=tk-inter",
    "--enable-plugin=matplotlib",
    "--prefer-source-code",
    "--assume-yes-for-downloads",
    "--show-progress",
    "--show-memory",
)


# Output directory mapping per target platform
PLATFORM_OUTPUT_DIRS: dict[str, str] = {
    "windows": "dist/Impulcifer_Distribution/ImpulciferGUI",
    "macos": "dist/macos",
    "linux": "dist/linux",
}

PLATFORM_OUTPUT_FILENAMES: dict[str, str] = {
    "windows": "ImpulciferGUI",
    "macos": "Impulcifer",
    "linux": "Impulcifer",
}


# ---------------------------------------------------------------------------
# Module / package inclusion lists
# ---------------------------------------------------------------------------
INCLUDED_PACKAGES: tuple[str, ...] = (
    # CustomTkinter ships JSON theme files and PNG assets that Nuitka's
    # static analysis won't pull in by import — keep as a package include.
    "customtkinter",
)

# Nuitka in --standalone mode follows static (and lazy) imports automatically,
# so the project tree (`core.*`, `gui.*`, `i18n.*`, `infra.*`, `updater.*`,
# `impulcifer`) does NOT need to be enumerated here — those entries were
# verified redundant against Nuitka 4.0's import tracer and removed.
#
# We keep explicit entries only for:
#   1. Heavyweight third-party packages that historically tripped Nuitka's
#      submodule detection (scipy / bokeh).
#   2. Modules that are entered through subprocess / multiprocessing rather
#      than the main thread's import graph (`core.parallel_workers`).
#   3. ``infra._build_info`` which is generated by ``build_nuitka.py`` just
#      before invocation — listed defensively in case the writeback is racy.
INCLUDED_MODULES: tuple[str, ...] = (
    # Heavy third-party — keep belt-and-suspenders for scipy/bokeh
    "scipy.signal",
    "scipy.optimize",
    "scipy.interpolate",
    "scipy.io",
    "scipy.fft",
    "bokeh",
    # Worker module loaded by ProcessPoolExecutor children
    "core.parallel_workers",
    # Build-time generated marker file
    "infra._build_info",
)


# ---------------------------------------------------------------------------
# Data assets — paths relative to project root
# ---------------------------------------------------------------------------
# Each entry is (source, destination_inside_bundle)
INCLUDED_DATA_DIRS: tuple[tuple[str, str], ...] = (
    ("data", "data"),
    ("font", "font"),
    ("img", "img"),
    ("i18n/locales", "i18n/locales"),
)

INCLUDED_DATA_FILES: tuple[tuple[str, str], ...] = (
    ("LICENSE", "License.txt"),
    ("README.txt", "README.txt"),
)


# ---------------------------------------------------------------------------
# Metadata flags (callers substitute version & description)
# ---------------------------------------------------------------------------
METADATA_TEMPLATE: tuple[str, ...] = (
    "--company-name=115dkk",
    "--product-name=Impulcifer",
    "--file-description=HRIR 측정 및 헤드폰 바이노럴 헤드트래킹 HRTF 시스템",
)


def platform_specific_flags(target_platform: str, project_root: str = ".") -> List[str]:
    """Return platform-conditional Nuitka flags.

    Includes window subsystem (Windows), app bundle (macOS), and icon
    inclusion when an icon file exists under ``project_root/img/``.
    """
    flags: List[str] = []
    if target_platform == "windows":
        flags.append("--windows-console-mode=disable")
    elif target_platform == "macos":
        flags.extend(("--macos-create-app-bundle", "--macos-app-name=Impulcifer"))
        icns = os.path.join(project_root, "img", "icon.icns")
        if os.path.exists(icns):
            flags.append(f"--macos-app-icon={icns}")
    elif target_platform == "linux":
        png = os.path.join(project_root, "img", "icon.png")
        if os.path.exists(png):
            flags.append(f"--linux-icon={png}")
    return flags


def build_nuitka_args(
    target_platform: str,
    version: str,
    project_root: str = ".",
    output_dir: Optional[str] = None,
    output_filename: Optional[str] = None,
    entry_point: str = "gui_main.py",
    jobs: Optional[int] = None,
) -> List[str]:
    """Assemble the complete argument list for ``python -m nuitka``.

    Returns the args without the leading ``["python", "-m", "nuitka"]``.
    The caller can prepend that or pass them to :func:`subprocess.run`.

    ``project_root`` is used to test for optional assets (icons, README.txt,
    LICENSE) so they are only included when they exist.

    ``jobs`` overrides the canonical ``--jobs=4`` from ``COMMON_FLAGS`` for
    callers that need a higher core count (e.g. local fast-iteration builds
    via ``build_scripts/build_local.py``). CI keeps the default of 4 since
    GitHub runners are not always 16-core.
    """
    if output_dir is None:
        output_dir = PLATFORM_OUTPUT_DIRS.get(target_platform, "dist")
    if output_filename is None:
        output_filename = PLATFORM_OUTPUT_FILENAMES.get(target_platform, "Impulcifer")

    if jobs is None:
        common_args = list(COMMON_FLAGS)
    else:
        # Replace the ``--jobs=N`` flag in COMMON_FLAGS so we don't end up
        # with a duplicated flag on the command line (Nuitka would error).
        common_args = [
            f"--jobs={jobs}" if a.startswith("--jobs=") else a
            for a in COMMON_FLAGS
        ]
    args: List[str] = common_args
    args.append(f"--output-dir={output_dir}")
    args.extend(platform_specific_flags(target_platform, project_root))

    for pkg in INCLUDED_PACKAGES:
        args.append(f"--include-package={pkg}")
    for mod in INCLUDED_MODULES:
        args.append(f"--include-module={mod}")

    for src, dst in INCLUDED_DATA_DIRS:
        full_src = os.path.join(project_root, src)
        if os.path.exists(full_src):
            args.append(f"--include-data-dir={src}={dst}")

    for src, dst in INCLUDED_DATA_FILES:
        full_src = os.path.join(project_root, src)
        if os.path.exists(full_src):
            args.append(f"--include-data-file={src}={dst}")

    args.extend(METADATA_TEMPLATE)
    args.append(f"--output-filename={output_filename}")
    args.append(f"--file-version={version}")
    args.append(f"--product-version={version}")
    args.append(entry_point)
    return args


def main(argv: Optional[Sequence[str]] = None) -> int:
    """Tiny CLI: ``python -m build_scripts.nuitka_flags --platform linux --version X``.

    Prints one Nuitka flag per line so a workflow can ``mapfile`` the output
    or feed it into a Nuitka invocation. Exists primarily to keep workflows
    in sync with this Python module without parsing it.
    """
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--platform",
        choices=("windows", "macos", "linux"),
        required=True,
        help="Target build platform.",
    )
    parser.add_argument(
        "--version",
        required=True,
        help="Project version string substituted into --file-version / --product-version.",
    )
    parser.add_argument(
        "--project-root",
        default=".",
        help="Path to the project root (defaults to CWD).",
    )
    args = parser.parse_args(argv)

    flag_list = build_nuitka_args(
        target_platform=args.platform,
        version=args.version,
        project_root=args.project_root,
    )
    for flag in flag_list:
        print(flag)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
