[package]
name = "impulcifer-dsp"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
impulcifer-types = { path = "../impulcifer-types" }
serde.workspace = true
serde_json = { workspace = true, features = ["float_roundtrip"] }
thiserror.workspace = true
rustfft.workspace = true
realfft.workspace = true
rayon.workspace = true

