//! Pipeline stage keys in the canonical order of 2.x
//! `core/pipeline.py::BRIRPipeline._stage_table`. Progress events carry these
//! keys verbatim so the frontend can map them without string matching.

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum StageKey {
    Estimator,
    RoomCorrection,
    HeadphoneCompensation,
    EqualizationFiles,
    Target,
    OpenMeasurements,
    PlotPre,
    CropAndAlign,
    VirtualBass,
    MicDeviationSkipped,
    MicDeviation,
    WriteResponses,
    Equalize,
    Decay,
    ChannelBalance,
    Normalize,
    WriteReadme,
    PlotPost,
    PlotResults,
    PlotAdditional,
    InteractivePlots,
    Resample,
    WriteBrirs,
    TruehdLayouts,
    Jamesdsp,
    Hangloose,
}

impl StageKey {
    pub const ORDER: [StageKey; 26] = [
        StageKey::Estimator,
        StageKey::RoomCorrection,
        StageKey::HeadphoneCompensation,
        StageKey::EqualizationFiles,
        StageKey::Target,
        StageKey::OpenMeasurements,
        StageKey::PlotPre,
        StageKey::CropAndAlign,
        StageKey::VirtualBass,
        StageKey::MicDeviationSkipped,
        StageKey::MicDeviation,
        StageKey::WriteResponses,
        StageKey::Equalize,
        StageKey::Decay,
        StageKey::ChannelBalance,
        StageKey::Normalize,
        StageKey::WriteReadme,
        StageKey::PlotPost,
        StageKey::PlotResults,
        StageKey::PlotAdditional,
        StageKey::InteractivePlots,
        StageKey::Resample,
        StageKey::WriteBrirs,
        StageKey::TruehdLayouts,
        StageKey::Jamesdsp,
        StageKey::Hangloose,
    ];

    pub fn key(self) -> &'static str {
        match self {
            StageKey::Estimator => "estimator",
            StageKey::RoomCorrection => "room_correction",
            StageKey::HeadphoneCompensation => "headphone_compensation",
            StageKey::EqualizationFiles => "equalization_files",
            StageKey::Target => "target",
            StageKey::OpenMeasurements => "open_measurements",
            StageKey::PlotPre => "plot_pre",
            StageKey::CropAndAlign => "crop_and_align",
            StageKey::VirtualBass => "virtual_bass",
            StageKey::MicDeviationSkipped => "mic_deviation_skipped",
            StageKey::MicDeviation => "mic_deviation",
            StageKey::WriteResponses => "write_responses",
            StageKey::Equalize => "equalize",
            StageKey::Decay => "decay",
            StageKey::ChannelBalance => "channel_balance",
            StageKey::Normalize => "normalize",
            StageKey::WriteReadme => "write_readme",
            StageKey::PlotPost => "plot_post",
            StageKey::PlotResults => "plot_results",
            StageKey::PlotAdditional => "plot_additional",
            StageKey::InteractivePlots => "interactive_plots",
            StageKey::Resample => "resample",
            StageKey::WriteBrirs => "write_brirs",
            StageKey::TruehdLayouts => "truehd_layouts",
            StageKey::Jamesdsp => "jamesdsp",
            StageKey::Hangloose => "hangloose",
        }
    }
}
