[package]
name = "impulcifer-audio-io"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
impulcifer-types = { path = "../impulcifer-types" }
thiserror.workspace = true
cpal = "0.18"

[target.'cfg(windows)'.dependencies]
impulcifer-sys-win = { path = "../impulcifer-sys-win" }

[dev-dependencies]
impulcifer-io = { path = "../impulcifer-io" }

[[bench]]
name = "perf"
harness = false
